const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),money=c=>"$"+(Number(c)/100).toLocaleString("es-MX",{minimumFractionDigits:2});
async function api(url,opt={}){const r=await fetch(url,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Error");return d}
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const toast=t=>{let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)};
async function boot(){try{let d=await api("/api/admin/me");$("#login").classList.add("hidden");$("#app").classList.remove("hidden");$("#adminName").textContent=d.admin.name;await Promise.all([stats(),users(),tickets(),events(),hotStatus(),raceStatus(),promotions(),notifications(),quinielas(),wallet(),audit(),settings(),supportConversations()])}catch{}}
async function stats(){const d=await api("/api/admin/stats");$("#usersTotal").textContent=d.users.total;$("#usersActive").textContent=d.users.active;$("#ticketsTotal").textContent=d.tickets.total;$("#balanceTotal").textContent=money(d.balances.balance);$("#requestsTotal").textContent=d.requests.pending;$("#eventsTotal").textContent=d.events.open}
async function users(){const q=$("#userSearch").value.trim();const d=await api('/api/admin/users?q='+encodeURIComponent(q));$("#usersBody").innerHTML=d.users.filter(u=>u.role!=="admin").map(u=>`<tr><td data-label="Usuario"><b>${esc(u.name)}</b><small>${new Date(u.created_at).toLocaleDateString('es-MX')}</small></td><td data-label="Contacto">${esc(u.email||"—")}<small>${esc(u.phone||"")}</small></td><td data-label="Saldo"><b>${money(u.balance_cents)}</b></td><td data-label="Estado"><span class="pill ${u.active?'ok':'off'}">${u.active?'Activo':'Bloqueado'}</span></td><td data-label="Acciones" class="actions-cell"><button class=action data-profile="${u.id}">Perfil</button><button class=action data-balance="${u.id}">Saldo</button><button class=action data-history="${u.id}">Historial</button><button class=action data-status="${u.id}" data-active="${u.active}">${u.active?'Bloquear':'Activar'}</button></td></tr>`).join("")||`<tr><td colspan=5>Sin usuarios.</td></tr>`;$$('[data-profile]').forEach(b=>b.onclick=()=>profileModal(b.dataset.profile));$$('[data-balance]').forEach(b=>b.onclick=()=>balanceModal(b.dataset.balance));$$('[data-history]').forEach(b=>b.onclick=()=>historyModal(b.dataset.history));$$('[data-status]').forEach(b=>b.onclick=()=>toggleUser(b.dataset.status,b.dataset.active==='true'))}
async function toggleUser(id,active){if(!confirm(active?'¿Bloquear este usuario?':'¿Activar este usuario?'))return;try{await api('/api/admin/users/'+id+'/status',{method:'PATCH',body:JSON.stringify({active:!active})});await Promise.all([stats(),users()]);toast('Estado actualizado')}catch(e){toast(e.message)}}
function openModal(title,html){$("#modalTitle").textContent=title;$("#modalContent").innerHTML=html;$("#modal").classList.remove('hidden')}
async function balanceModal(id,direction=1){
  openModal('Ajustar saldo',`<p>El importe se captura en pesos mexicanos. Usa un número positivo para <b>agregar crédito</b> y negativo para <b>descontar</b>.</p><div class=formgrid><input id=amount type=number step="0.01" min="-1000000" placeholder="Ej. 500"><input id=reason placeholder="Motivo, ej. Depósito manual"></div><button id=saveBalance class="primary">Aplicar movimiento</button>`);
  $("#saveBalance").onclick=async()=>{
    try{
      const pesos=Number($("#amount").value),reason=$("#reason").value.trim();
      if(!Number.isFinite(pesos)||pesos===0||!reason)return toast("Indica un monto y un motivo");
      const amountCents=Math.round(Math.abs(pesos)*100)*direction;
      await api('/api/admin/users/'+id+'/balance',{method:'POST',body:JSON.stringify({amountCents,reason})});
      $("#modal").classList.add('hidden');await Promise.all([stats(),users()]);toast('Saldo actualizado ✓');
    }catch(e){toast(e.message)}
  }
}
async function profileModal(id){
  try{
    const d=await api('/api/admin/users/'+id);
    const u=d.user;
    const tx=d.transactions||[], req=d.requests||[], tickets=d.tickets||[];
    openModal('Perfil del jugador',`
      <div class="profile-admin">
        <div><b>${esc(u.name)}</b><small>${esc(u.email||u.phone||'Sin contacto')}</small></div>
        <div><b>Saldo actual</b><strong>${money(u.balance_cents)}</strong></div>
        <div class="formgrid">
          <button class="primary" id="addCredit">+ Agregar crédito</button>
          <button class="action" id="removeCredit">− Descontar saldo</button>
        </div>
        <button class="action" id="editUser">Editar datos del jugador</button>
        <p><small>Creada: ${new Date(u.created_at).toLocaleString('es-MX')} · Estado: ${u.active?'Activa':'Bloqueada'}</small></p>
      </div>
      <hr><h3>Solicitudes de depósito/retiro</h3>
      ${req.length?`<div class="history">${req.map(r=>`<div><b>${r.type==='DEPOSIT'?'Depósito':'Retiro'} · ${money(r.amount_cents)}</b> · ${esc(r.status)}<br><small>${esc(r.note||'Sin nota')} · ${new Date(r.created_at).toLocaleString('es-MX')}</small></div>`).join('')}</div>`:'<p>Sin solicitudes.</p>'}
      <hr><h3>Movimientos</h3>
      ${tx.length?`<div class="history">${tx.map(t=>`<div><b class="${Number(t.amount_cents)>=0?'ok':'danger'}">${Number(t.amount_cents)>=0?'+':''}${money(t.amount_cents)}</b> · saldo ${money(t.balance_after_cents)}<br><small>${esc(t.reason)} · ${new Date(t.created_at).toLocaleString('es-MX')}</small></div>`).join('')}</div>`:'<p>Sin movimientos.</p>'}
      <hr><h3>Últimos tickets</h3>
      ${tickets.length?`<div class="history">${tickets.map(t=>`<div><b>${money(t.stake_cents)} · ${Number(t.total_odds).toFixed(2)}</b> · ${esc(t.status)}<br><small>${new Date(t.created_at).toLocaleString('es-MX')}</small></div>`).join('')}</div>`:'<p>Sin tickets.</p>'}
    `);
    $("#addCredit").onclick=()=>{ $("#modal").classList.add('hidden'); balanceModal(id); setTimeout(()=>{$("#amount").value="";$("#reason").value="Depósito manual";$("#amount").focus()},0); };
    $("#removeCredit").onclick=()=>{ $("#modal").classList.add('hidden'); balanceModal(id,-1); setTimeout(()=>{$("#amount").value="";$("#reason").value="Ajuste administrativo";$("#amount").focus()},0); };
    $("#editUser").onclick=()=>{
      openModal('Editar jugador',`<div class="formgrid"><input id="editName" value="${esc(u.name)}" placeholder="Nombre"><input id="editPhone" value="${esc(u.phone||'')}" placeholder="Teléfono"></div><p><small>Correo: ${esc(u.email||'—')} (no editable aquí)</small></p><button id="saveUser" class="primary">Guardar cambios</button>`);
      $("#saveUser").onclick=async()=>{try{await api('/api/admin/users/'+id,{method:'PATCH',body:JSON.stringify({name:$("#editName").value,phone:$("#editPhone").value})});await users();await profileModal(id);toast('Jugador actualizado ✓')}catch(e){toast(e.message)}};
    };
  }catch(e){toast(e.message)}
}
async function historyModal(id){try{const d=await api('/api/admin/users/'+id+'/transactions');openModal('Historial de saldo',d.transactions.length?`<div class=history>${d.transactions.map(t=>`<div><b class=${Number(t.amount_cents)>=0?'ok':'danger'}>${Number(t.amount_cents)>=0?'+':''}${money(t.amount_cents)}</b> · saldo ${money(t.balance_after_cents)}<br><small>${esc(t.type)} · ${esc(t.reason)} · ${esc(t.admin_name)} · ${new Date(t.created_at).toLocaleString('es-MX')}</small></div>`).join('')}</div>`:'<p>Sin movimientos.</p>')}catch(e){toast(e.message)}}
async function tickets(){const d=await api('/api/admin/tickets');$('#ticketsBody').innerHTML=d.tickets.map(t=>`<tr><td data-label="Usuario"><b>${esc(t.user_name)}</b><small>${esc(t.user_email||'')}</small></td><td data-label="Importe">${money(t.stake_cents)}</td><td data-label="Cuota">${Number(t.total_odds).toFixed(2)}</td><td data-label="Potencial">${money(t.potential_cents)}</td><td data-label="Estado"><span class=pill>${esc(t.status)}</span></td><td data-label="Fecha">${new Date(t.created_at).toLocaleString('es-MX')}</td><td data-label="Liquidación">Automática</td></tr>`).join('')||'<tr><td colspan=7>Sin tickets.</td></tr>'} 
async function hotStatus(){
  try{
    const d=await api("/api/admin/hot/status");
    $("#hotSummary").innerHTML=`<b>🔥 HOT 2H2</b> · ${d.enabled?"Activo":"Pausado"} · Cada ${d.intervalMinutes} min · Duración ${d.durationMinutes} min · Rotación ${d.rotationHours} h · Fútbol ${d.hours.football} · Otros ${d.hours.other}<br><small>En vivo: ${d.counts.live} · Próximos: ${d.counts.upcoming}</small>`;
    $("#hotBody").innerHTML=(d.events||[]).map(e=>`<tr><td><b>${esc(e.home_team)} vs ${esc(e.away_team)}</b><small>${esc(e.league)}</small></td><td>${esc(e.sport)}</td><td>${new Date(e.starts_at).toLocaleString('es-MX')}</td><td><span class=pill>${esc(e.status)}${e.hot_locked?' · FIJO':''}</span></td><td><b>${e.home_score??0} - ${e.away_score??0}</b><small>${e.live_elapsed??0}'</small></td><td class="actions-cell"><button class=action data-hot-control="${e.id}">Controlar</button></td></tr>`).join("")||'<tr><td colspan=6>Sin HOT.</td></tr>';
    $$('[data-hot-control]').forEach(b=>b.onclick=()=>hotControl(b.dataset.hotControl));
  }catch(e){toast(e.message)}
}
async function hotControl(id){
  try{
    const d=await api("/api/admin/events/"+id);const e=d.event;
    openModal("Control HOT",`<p><b>${esc(e.home_team)} vs ${esc(e.away_team)}</b></p>
      <div class=formgrid><input id=hotHome type=number min=0 value="${e.home_score||0}" placeholder="Marcador local">
      <input id=hotAway type=number min=0 value="${e.away_score||0}" placeholder="Marcador visitante">
      <input id=hotElapsed type=number min=0 max=8 value="${e.live_elapsed||0}" placeholder="Minuto 0-8">
      <select id=hotStatus><option value="LIVE">EN VIVO</option><option value="OPEN">PRÓXIMO</option><option value="CLOSED">FINALIZADO</option></select>
      <select id=hotWinner><option value="">Ganador automático</option><option value="L">Local</option><option value="E">Empate</option><option value="V">Visitante</option></select></div>
      <label><input id=hotLock type=checkbox checked> Fijar resultado y detener automatización</label>
      <button id=hotSave class=primary>Guardar control</button>`);
    $("#hotStatus").value=e.status==="CLOSED"?"CLOSED":e.status==="OPEN"?"OPEN":"LIVE";
    $("#hotWinner").value=e.hot_winner||"";
    $("#hotSave").onclick=async()=>{try{
      await api("/api/admin/hot/event/"+id+"/control",{method:"POST",body:JSON.stringify({status:$("#hotStatus").value,homeScore:Number($("#hotHome").value),awayScore:Number($("#hotAway").value),elapsed:Number($("#hotElapsed").value),winner:$("#hotWinner").value,locked:$("#hotLock").checked})});
      $("#modal").classList.add("hidden");await hotStatus();await events();toast("HOT actualizado");
    }catch(e){toast(e.message)}};
  }catch(e){toast(e.message)}
}
async function events(){const d=await api('/api/admin/events');$("#eventsBody").innerHTML=d.events.map(e=>`<tr><td data-label="Evento"><b>${esc(e.home_team)} vs ${esc(e.away_team)}</b><small>${esc(e.league)}</small></td><td data-label="Deporte">${esc(e.sport)}</td><td data-label="Inicio">${new Date(e.starts_at).toLocaleString('es-MX')}</td><td data-label="Estado"><span class=pill>${esc(e.status)}</span></td><td data-label="Selecciones">${e.selections_count}</td><td data-label="Acciones" class="actions-cell"><button class=action data-markets="${e.id}">Mercados</button><button class=action data-live-event="${e.id}">En vivo</button><button class=action data-home-score="${e.id}">+ Local</button><button class=action data-away-score="${e.id}">+ Visitante</button><button class=action data-finish-event="${e.id}">Finalizar</button><button class=action data-close-event="${e.id}">Cerrar</button><button class=action data-delete-event="${e.id}">Eliminar</button></td></tr>`).join('')||'<tr><td colspan=6>Sin eventos.</td></tr>';$$('[data-markets]').forEach(b=>b.onclick=()=>marketsModal(b.dataset.markets));$$('[data-live-event]').forEach(b=>b.onclick=()=>updateEvent(b.dataset.liveEvent,{status:'LIVE',liveElapsed:0,liveStatus:'En vivo (BetLive)'}));$$('[data-home-score]').forEach(b=>b.onclick=()=>scoreEvent(b.dataset.homeScore,'home'));$$('[data-away-score]').forEach(b=>b.onclick=()=>scoreEvent(b.dataset.awayScore,'away'));$$('[data-finish-event]').forEach(b=>b.onclick=()=>updateEvent(b.dataset.finishEvent,{status:'CLOSED',liveStatus:'Finalizado'}));$$('[data-close-event]').forEach(b=>b.onclick=()=>updateEvent(b.dataset.closeEvent,{status:'CLOSED'}));$$('[data-delete-event]').forEach(b=>b.onclick=()=>deleteEvent(b.dataset.deleteEvent))}
function newEvent(){openModal('Nuevo evento',`<div class=formgrid><input id=esport placeholder="Deporte"><input id=eleague placeholder="Liga"><input id=ehome placeholder="Local"><input id=eaway placeholder="Visitante"><input id=estarts type=datetime-local><select id=efeatured><option value=false>Normal</option><option value=true>Destacado</option></select><select id=evideo><option value=false>Sin video</option><option value=true>Video</option></select></div><button id=saveEvent class=primary>Crear evento</button>`);$("#saveEvent").onclick=async()=>{try{await api('/api/admin/events',{method:'POST',body:JSON.stringify({sport:$("#esport").value,league:$("#eleague").value,homeTeam:$("#ehome").value,awayTeam:$("#eaway").value,startsAt:$("#estarts").value,featured:$("#efeatured").value==='true',video:$("#evideo").value==='true'})});$("#modal").classList.add('hidden');await Promise.all([events(),stats()]);toast('Evento creado')}catch(e){toast(e.message)}}}

async function scoreEvent(id,side){try{const d=await api('/api/admin/events/'+id);const e=d.event||{};const key=side==='home'?'homeScore':'awayScore';const next=Math.max(0,Number(e[key]||0)+1);await updateEvent(id,{status:'LIVE',[key]:next,liveElapsed:e.live_elapsed||0,liveStatus:'En vivo (BetLive)'});}catch(e){toast(e.message)}}
async function updateEvent(id,body){try{await api('/api/admin/events/'+id,{method:'PATCH',body:JSON.stringify(body)});await events();toast('Evento actualizado')}catch(e){toast(e.message)}}
async function deleteEvent(id){if(!confirm('¿Eliminar este evento y sus mercados?'))return;try{await api('/api/admin/events/'+id,{method:'DELETE'});await Promise.all([events(),stats()]);toast('Evento eliminado')}catch(e){toast(e.message)}}
async function marketsModal(eventId){try{const d=await api('/api/admin/events/'+eventId+'/markets');openModal('Mercados y cuotas',`<div class=history>${d.markets.map(m=>`<div><b>${esc(m.name)}</b>${(m.selections||[]).map(s=>`<p>${esc(s.label)} <b>${Number(s.odds).toFixed(2)}</b> <button class=action data-odd="${s.id}">Editar cuota</button></p>`).join('')}</div>`).join('')||'<p>Sin mercados.</p>'}</div><hr><h3>Agregar mercado</h3><div class=formgrid><input id=mname placeholder="Nombre, ej. Más/Menos 2.5"><input id=mtype placeholder="Tipo"></div><textarea id=msels rows=5 placeholder='Una selección por línea: Local|1|1.80'></textarea><button id=saveMarket class=primary>Agregar mercado</button>`);$$('[data-odd]').forEach(b=>b.onclick=()=>editOdd(b.dataset.odd,eventId));$("#saveMarket").onclick=async()=>{try{const selections=$("#msels").value.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const p=x.split('|');return{label:p[0],code:p[1]||'',odds:Number(p[2])}});await api('/api/admin/events/'+eventId+'/markets',{method:'POST',body:JSON.stringify({name:$("#mname").value,marketType:$("#mtype").value||'CUSTOM',selections})});await marketsModal(eventId);toast('Mercado creado')}catch(e){toast(e.message)}}}catch(e){toast(e.message)}}
async function editOdd(id,eventId){const v=prompt('Nueva cuota');if(v===null)return;try{await api('/api/admin/selections/'+id,{method:'PATCH',body:JSON.stringify({odds:Number(v)})});await marketsModal(eventId);toast('Cuota actualizada')}catch(e){toast(e.message)}}
async function quinielas(){const d=await api('/api/admin/quinielas');$("#quinielasBody").innerHTML=d.quinielas.map(q=>`<tr><td data-label="Nombre"><b>${esc(q.name)}</b><small>${esc(q.description||'')}</small></td><td data-label="Tipo">${esc(q.kind)}</td><td data-label="Precio">${money(q.price_cents)}</td><td data-label="Cierre">${q.close_at?new Date(q.close_at).toLocaleString('es-MX'):'—'}</td><td data-label="Estado"><span class=pill>${q.active?'Activa':'Inactiva'}</span></td><td data-label="Acciones" class="actions-cell"><button class=action data-toggle-q="${q.id}" data-active="${q.active}">${q.active?'Desactivar':'Activar'}</button></td></tr>`).join('')||'<tr><td colspan=6>Sin quinielas.</td></tr>';$$('[data-toggle-q]').forEach(b=>b.onclick=()=>toggleQ(b.dataset.toggleQ,b.dataset.active==='true'))}
function newQuiniela(){openModal('Nueva quiniela',`<div class=formgrid><input id=qname placeholder="Nombre"><input id=qkind placeholder="Tipo: FACIL"><input id=qprice type=number placeholder="Precio en centavos"><input id=qclose type=datetime-local></div><textarea id=qdesc rows=3 placeholder="Descripción"></textarea><input id=qprize placeholder="Texto de premios"><button id=saveQ class=primary>Crear quiniela</button>`);$("#saveQ").onclick=async()=>{try{await api('/api/admin/quinielas',{method:'POST',body:JSON.stringify({name:$("#qname").value,kind:$("#qkind").value,priceCents:Number($("#qprice").value),closeAt:$("#qclose").value||null,description:$("#qdesc").value,prizeText:$("#qprize").value})});$("#modal").classList.add('hidden');await quinielas();toast('Quiniela creada')}catch(e){toast(e.message)}}}
async function toggleQ(id,active){try{await api('/api/admin/quinielas/'+id,{method:'PATCH',body:JSON.stringify({active:!active})});await quinielas();toast('Quiniela actualizada')}catch(e){toast(e.message)}}
async function wallet(){const d=await api('/api/admin/wallet-requests');$("#walletBody").innerHTML=d.requests.map(r=>`<tr><td data-label="Usuario"><b>${esc(r.user_name)}</b><small>${esc(r.user_email||'')} · ${esc(r.user_phone||'')}</small></td><td data-label="Tipo">${r.type==='DEPOSIT'?'Depósito':'Retiro'}<small>${esc(r.note||'')}</small>${r.type==='WITHDRAWAL'&&r.payout_details?`<div class="payout"><b>${esc(r.payout_details.method||'')}</b> · ${esc(r.payout_details.bank||'')}<br>${esc(r.payout_details.accountHolder||'')} · CLABE ${esc(r.payout_details.clabe||r.payout_details.accountNumber||'')}<br>Tel. ${esc(r.payout_details.phone||'')}</div>`:''}</td><td data-label="Monto">${money(r.amount_cents)}</td><td data-label="Estado"><span class=pill>${esc(r.status)}</span></td><td data-label="Fecha">${new Date(r.created_at).toLocaleString('es-MX')}</td><td data-label="Acciones" class="actions-cell wallet-actions">${r.status==='PENDING'?`<button class="action primary" data-wallet="${r.id}" data-ws="APPROVED">${r.type==='DEPOSIT'?'Acreditar depósito':'Autorizar retiro'}</button><button class="action" data-wallet="${r.id}" data-ws="REJECTED">Rechazar</button>`:r.status==='APPROVED'&&r.type==='WITHDRAWAL'?`<button class="action primary" data-paid="${r.id}">Marcar pagado</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan=6>Sin solicitudes.</td></tr>';$$('[data-wallet]').forEach(b=>b.onclick=()=>resolveWallet(b.dataset.wallet,b.dataset.ws));$$("[data-paid]").forEach(b=>b.onclick=()=>payWithdrawal(b.dataset.paid))}
async function resolveWallet(id,status){if(!confirm(status==='APPROVED'?'¿Aprobar y acreditar automáticamente este depósito en la cuenta del participante?':'¿Rechazar esta solicitud?'))return;try{const d=await api('/api/admin/wallet-requests/'+id+'/resolve',{method:'POST',body:JSON.stringify({status})});await Promise.all([wallet(),stats()]);toast(status==='APPROVED'&&d.balance_cents!==null?'Depósito acreditado automáticamente ✓':'Solicitud actualizada')}catch(e){toast(e.message)}}
async function payWithdrawal(id){if(!confirm("¿Confirmas que ya realizaste el pago de este retiro?"))return;try{await api('/api/admin/wallet-requests/'+id+'/paid',{method:'POST'});await Promise.all([wallet(),stats()]);toast('Retiro marcado como pagado ✓')}catch(e){toast(e.message)}}
async function settings(){
  try{
    const d=await api('/api/admin/wallet-settings'),s=d.settings||{};
    $("#settingsForm").innerHTML=`
      <label>Activo<select id="wsEnabled"><option value="true" ${s.enabled?'selected':''}>Sí</option><option value="false" ${!s.enabled?'selected':''}>No</option></select></label>
      <label>Título<input id="wsTitle" value="${esc(s.title||'')}"></label>
      <label>Banco<input id="wsBank" value="${esc(s.bank_name||'')}"></label>
      <label>Titular<input id="wsHolder" value="${esc(s.account_holder||'')}"></label>
      <label>Número de cuenta<input id="wsAccount" value="${esc(s.account_number||'')}"></label>
      <label>CLABE<input id="wsClabe" value="${esc(s.clabe||'')}"></label>
      <label>Tarjeta<input id="wsCard" value="${esc(s.card_number||'')}"></label>
      <label>Referencia<input id="wsRef" value="${esc(s.reference_text||'')}"></label>
      <label>Instrucciones<textarea id="wsInstructions" rows="5">${esc(s.instructions||'')}</textarea></label>
      <button id="saveSettings" class="primary">Guardar datos de depósito</button>`;
    $("#saveSettings").onclick=async()=>{
      try{await api('/api/admin/wallet-settings',{method:'PATCH',body:JSON.stringify({enabled:$("#wsEnabled").value==='true',title:$("#wsTitle").value,bank_name:$("#wsBank").value,account_holder:$("#wsHolder").value,account_number:$("#wsAccount").value,clabe:$("#wsClabe").value,card_number:$("#wsCard").value,reference_text:$("#wsRef").value,instructions:$("#wsInstructions").value})});toast('Datos de depósito guardados ✓')}catch(e){toast(e.message)}
    };
  }catch(e){toast(e.message)}
}
let selectedSupportUser=null,supportAdminTimer=null;
async function supportConversations(){try{const d=await api('/api/admin/support/conversations');$("#supportConversations").innerHTML=d.conversations.map(c=>`<button class="support-conv ${selectedSupportUser===c.user_id?'active':''}" data-support-user="${c.user_id}"><b>${esc(c.name)}</b><small>${esc(c.email||c.phone||'')} · ${c.unread?c.unread+' sin leer':''}</small></button>`).join('')||'<div class=empty>Sin conversaciones todavía.</div>';$$('[data-support-user]').forEach(b=>b.onclick=()=>openAdminSupport(b.dataset.supportUser,b.querySelector('b').textContent));}catch(e){toast(e.message)}}
async function loadAdminSupport(){if(!selectedSupportUser)return;try{const d=await api('/api/admin/support/'+selectedSupportUser+'/messages');$("#supportAdminMessages").innerHTML=d.messages.map(m=>`<div class="support-msg ${m.sender_role==='ADMIN'?'mine':'admin'}"><b>${m.sender_role==='ADMIN'?'Tú':'Jugador'}</b><p>${esc(m.message)}</p><small>${new Date(m.created_at).toLocaleString('es-MX')}</small></div>`).join('')||'<div class=empty>Sin mensajes.</div>';const box=$("#supportAdminMessages");box.scrollTop=box.scrollHeight;}catch(e){toast(e.message)}}
function openAdminSupport(id,name){selectedSupportUser=id;$("#supportChatTitle").textContent='Chat con '+name;loadAdminSupport();clearInterval(supportAdminTimer);supportAdminTimer=setInterval(()=>{loadAdminSupport();supportConversations()},5000);supportConversations()}
$("#refreshSupport").onclick=()=>{supportConversations();loadAdminSupport()};
$("#supportAdminSend").onclick=async()=>{try{if(!selectedSupportUser)return toast('Selecciona un jugador');const input=$("#supportAdminInput"),message=input.value.trim();if(!message)return toast('Escribe un mensaje');await api('/api/admin/support/'+selectedSupportUser+'/messages',{method:'POST',body:JSON.stringify({message})});input.value='';await loadAdminSupport();await supportConversations()}catch(e){toast(e.message)}};
async function audit(){const d=await api('/api/admin/audit');$("#auditBody").innerHTML=d.audit.map(a=>`<tr><td data-label="Administrador">${esc(a.admin_name)}</td><td data-label="Acción">${esc(a.action)}</td><td data-label="Objetivo">${esc(a.target_type||'')}<small>${esc(a.target_id||'')}</small></td><td data-label="Detalles"><small>${esc(JSON.stringify(a.details||{}))}</small></td><td data-label="Fecha">${new Date(a.created_at).toLocaleString('es-MX')}</td></tr>`).join('')||'<tr><td colspan=5>Sin registros.</td></tr>'}
$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent='';try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({identifier:$("#email").value,password:$("#password").value})});await boot();if(!$("#app").classList.contains('hidden'))toast('Sesión iniciada')}catch(e){$("#loginError").textContent=e.message}};
$("#adminMenu").onclick=()=>$("#adminDrawer").classList.remove("hidden");$("#closeAdminDrawer").onclick=()=>$("#adminDrawer").classList.add("hidden");
$("#logout").onclick=async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()};$("#closeModal").onclick=()=>$("#modal").classList.add('hidden');$("#refreshUsers").onclick=users;$("#refreshTickets").onclick=tickets;$("#refreshEvents").onclick=events;$("#refreshQuinielas").onclick=quinielas;$("#refreshWallet").onclick=wallet;$("#refreshAudit").onclick=audit;$("#refreshSettings").onclick=settings;$("#newEvent").onclick=newEvent;$("#newQuiniela").onclick=newQuiniela;$("#userSearch").oninput=()=>users();
$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$("#adminDrawer").classList.add('hidden');['users','tickets','events','races','promotions','notifications','hot','quinielas','wallet','audit','settings','support'].forEach(v=>$("#"+v+"View").classList.toggle('hidden',b.dataset.view!==v))});boot();

$("#hotGenerate")?.addEventListener("click",async()=>{try{await api("/api/admin/hot/generate",{method:"POST"});await hotStatus();await stats();toast("HOT generado/actualizado")}catch(e){toast(e.message)}});
$("#hotRefresh")?.addEventListener("click",hotStatus);

async function raceStatus(){try{const d=await api('/api/admin/races/status');$('#raceSummary').innerHTML=`<b>🏎️ Carreras</b> · ${d.enabled?'Activo':'Pausado'} · Cada ${d.intervalMinutes} min · Duración ${d.durationMinutes} min · Rotación ${d.rotationHours} h<br><small>En vivo: ${d.counts.live} · Próximas: ${d.counts.upcoming} · Cerradas: ${d.counts.closed}</small>`;$('#raceBody').innerHTML=(d.events||[]).map(e=>`<tr><td><b>${esc(e.home_team)} vs ${esc(e.away_team)}</b><small>${esc(e.league)}</small></td><td>${new Date(e.starts_at).toLocaleString('es-MX')}</td><td><span class=pill>${esc(e.status)}${e.race_locked?' · FIJA':''}</span></td><td>${e.live_elapsed??0}'</td><td>${esc(e.race_winner||'—')}</td><td><button class=action data-race-control="${e.id}">Controlar</button></td></tr>`).join('')||'<tr><td colspan=6>Sin carreras.</td></tr>';$$('[data-race-control]').forEach(b=>b.onclick=()=>raceControl(b.dataset.raceControl))}catch(e){toast(e.message)}}
async function raceControl(id){try{const d=await api('/api/admin/races/status');const e=d.events.find(x=>x.id===id);if(!e)return;openModal('Control de carrera',`<p><b>${esc(e.home_team)} vs ${esc(e.away_team)}</b></p><div class=formgrid><input id=raceElapsed type=number min=0 max=6 value="${e.live_elapsed||0}"><select id=raceStatus><option>OPEN</option><option>LIVE</option><option>CLOSED</option></select><input id=raceWinner placeholder="Ganador / piloto"></div><label><input id=raceLock type=checkbox checked> Fijar y detener automatización</label><button id=raceSave class=primary>Guardar</button>`);$('#raceStatus').value=e.status;$('#raceSave').onclick=async()=>{try{await api('/api/admin/races/event/'+id+'/control',{method:'POST',body:JSON.stringify({elapsed:Number($('#raceElapsed').value),status:$('#raceStatus').value,winner:$('#raceWinner').value,locked:$('#raceLock').checked})});$('#modal').classList.add('hidden');await raceStatus();toast('Carrera actualizada')}catch(x){toast(x.message)}}}catch(e){toast(e.message)}}
async function promotions(){try{const d=await api('/api/admin/promotions');$('#promotionsBody').innerHTML=d.promotions.map(p=>`<tr><td><b>${esc(p.title)}</b><small>${esc(p.body)}</small></td><td>${esc(p.promo_kind)}</td><td>${p.bonus_cents?money(p.bonus_cents):'Informativa'}</td><td>${new Date(p.starts_at).toLocaleDateString('es-MX')} · ${p.ends_at?new Date(p.ends_at).toLocaleDateString('es-MX'):'Sin fin'}</td><td><span class=pill>${p.active?'Activa':'Inactiva'}</span></td><td><button class=action data-promo-toggle="${p.id}" data-active="${p.active}">${p.active?'Desactivar':'Activar'}</button></td></tr>`).join('')||'<tr><td colspan=6>Sin promociones.</td></tr>';$$('[data-promo-toggle]').forEach(b=>b.onclick=async()=>{try{await api('/api/admin/promotions/'+b.dataset.promoToggle,{method:'PATCH',body:JSON.stringify({active:b.dataset.active!=='true'})});await promotions()}catch(e){toast(e.message)}})}catch(e){toast(e.message)}}
function newPromotion(){openModal('Nueva promoción',`<div class=formgrid><input id=promoTitle placeholder="Título"><select id=promoKind><option>INFO</option><option>BONUS</option><option>EVENT</option></select><input id=promoBonus type=number min=0 placeholder="Beneficio en centavos"><input id=promoMin type=number min=0 placeholder="Mínimo depósito en centavos"><input id=promoStart type=datetime-local><input id=promoEnd type=datetime-local></div><textarea id=promoBody rows=4 placeholder="Mensaje"></textarea><textarea id=promoTerms rows=3 placeholder="Condiciones y vigencia"></textarea><button id=savePromo class=primary>Crear promoción</button>`);$('#savePromo').onclick=async()=>{try{await api('/api/admin/promotions',{method:'POST',body:JSON.stringify({title:$('#promoTitle').value,body:$('#promoBody').value,promoKind:$('#promoKind').value,bonusCents:Number($('#promoBonus').value)||0,minDepositCents:Number($('#promoMin').value)||0,startsAt:$('#promoStart').value||null,endsAt:$('#promoEnd').value||null,terms:$('#promoTerms').value})});$('#modal').classList.add('hidden');await promotions();toast('Promoción creada')}catch(e){toast(e.message)}}}
async function notifications(){try{const d=await api('/api/admin/notifications');$('#notificationsBody').innerHTML=d.notifications.map(n=>`<tr><td>${esc(n.user_name)}</td><td><b>${esc(n.title)}</b></td><td>${esc(n.body)}</td><td>${new Date(n.created_at).toLocaleString('es-MX')}</td></tr>`).join('')||'<tr><td colspan=4>Sin notificaciones.</td></tr>'}catch(e){toast(e.message)}}
function newNotification(){openModal('Nueva notificación',`<div class=formgrid><input id=notifTitle placeholder="Título"><select id=notifKind><option>INFO</option><option>EVENT</option><option>PROMO</option><option>SYSTEM</option></select><input id=notifUser placeholder="ID de usuario (vacío = todos)"></div><textarea id=notifBody rows=4 placeholder="Mensaje"></textarea><button id=saveNotif class=primary>Enviar</button>`);$('#saveNotif').onclick=async()=>{try{await api('/api/admin/notifications',{method:'POST',body:JSON.stringify({title:$('#notifTitle').value,body:$('#notifBody').value,kind:$('#notifKind').value,userId:$('#notifUser').value||null})});$('#modal').classList.add('hidden');await notifications();toast('Notificación enviada')}catch(e){toast(e.message)}}}
$('#raceGenerate')?.addEventListener('click',async()=>{try{await api('/api/admin/races/generate',{method:'POST'});await raceStatus();toast('Carreras generadas')}catch(e){toast(e.message)}});$('#raceRefresh')?.addEventListener('click',raceStatus);$('#newPromotion')?.addEventListener('click',newPromotion);$('#refreshPromotions')?.addEventListener('click',promotions);$('#newNotification')?.addEventListener('click',newNotification);$('#refreshNotifications')?.addEventListener('click',notifications);
