const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),money=c=>"$"+(Number(c)/100).toLocaleString("es-MX",{minimumFractionDigits:2});
async function api(url,opt={}){const r=await fetch(url,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Error");return d}
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const toast=t=>{let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)};
async function boot(){try{let d=await api("/api/admin/me");$("#login").classList.add("hidden");$("#app").classList.remove("hidden");$("#adminName").textContent=d.admin.name;await Promise.all([stats(),users(),tickets(),events(),quinielas(),wallet(),audit()])}catch{}}
async function stats(){const d=await api("/api/admin/stats");$("#usersTotal").textContent=d.users.total;$("#usersActive").textContent=d.users.active;$("#ticketsTotal").textContent=d.tickets.total;$("#balanceTotal").textContent=money(d.balances.balance);$("#requestsTotal").textContent=d.requests.pending;$("#eventsTotal").textContent=d.events.open}
async function users(){const q=$("#userSearch").value.trim();const d=await api('/api/admin/users?q='+encodeURIComponent(q));$("#usersBody").innerHTML=d.users.filter(u=>u.role!=="admin").map(u=>`<tr><td><b>${esc(u.name)}</b><small>${new Date(u.created_at).toLocaleDateString('es-MX')}</small></td><td>${esc(u.email||"—")}<small>${esc(u.phone||"")}</small></td><td><b>${money(u.balance_cents)}</b></td><td><span class="pill ${u.active?'ok':'off'}">${u.active?'Activo':'Bloqueado'}</span></td><td><button class=action data-balance="${u.id}">Saldo</button><button class=action data-history="${u.id}">Historial</button><button class=action data-status="${u.id}" data-active="${u.active}">${u.active?'Bloquear':'Activar'}</button></td></tr>`).join("")||`<tr><td colspan=5>Sin usuarios.</td></tr>`;$$('[data-balance]').forEach(b=>b.onclick=()=>balanceModal(b.dataset.balance));$$('[data-history]').forEach(b=>b.onclick=()=>historyModal(b.dataset.history));$$('[data-status]').forEach(b=>b.onclick=()=>toggleUser(b.dataset.status,b.dataset.active==='true'))}
async function toggleUser(id,active){if(!confirm(active?'¿Bloquear este usuario?':'¿Activar este usuario?'))return;try{await api('/api/admin/users/'+id+'/status',{method:'PATCH',body:JSON.stringify({active:!active})});await Promise.all([stats(),users()]);toast('Estado actualizado')}catch(e){toast(e.message)}}
function openModal(title,html){$("#modalTitle").textContent=title;$("#modalContent").innerHTML=html;$("#modal").classList.remove('hidden')}
async function balanceModal(id){openModal('Modificar saldo',`<p>Usa centavos: <b>10000</b> = $100.00. Negativo = retiro administrativo.</p><div class=formgrid><input id=amount type=number placeholder="Monto en centavos"><input id=reason placeholder="Motivo"></div><button id=saveBalance class="primary">Aplicar movimiento</button>`);$("#saveBalance").onclick=async()=>{try{await api('/api/admin/users/'+id+'/balance',{method:'POST',body:JSON.stringify({amountCents:Number($("#amount").value),reason:$("#reason").value})});$("#modal").classList.add('hidden');await Promise.all([stats(),users()]);toast('Saldo actualizado')}catch(e){toast(e.message)}}}
async function historyModal(id){try{const d=await api('/api/admin/users/'+id+'/transactions');openModal('Historial de saldo',d.transactions.length?`<div class=history>${d.transactions.map(t=>`<div><b class=${Number(t.amount_cents)>=0?'ok':'danger'}>${Number(t.amount_cents)>=0?'+':''}${money(t.amount_cents)}</b> · saldo ${money(t.balance_after_cents)}<br><small>${esc(t.type)} · ${esc(t.reason)} · ${esc(t.admin_name)} · ${new Date(t.created_at).toLocaleString('es-MX')}</small></div>`).join('')}</div>`:'<p>Sin movimientos.</p>')}catch(e){toast(e.message)}}
async function tickets(){const d=await api('/api/admin/tickets');$("#ticketsBody").innerHTML=d.tickets.map(t=>`<tr><td><b>${esc(t.user_name)}</b><small>${esc(t.user_email||'')}</small></td><td>${money(t.stake_cents)}</td><td>${Number(t.total_odds).toFixed(2)}</td><td>${money(t.potential_cents)}</td><td><span class=pill>${esc(t.status)}</span></td><td>${new Date(t.created_at).toLocaleString('es-MX')}</td><td>${t.status==='PENDING'?`<button class="action" data-settle="${t.id}" data-s="WON">Ganar</button><button class="action" data-settle="${t.id}" data-s="LOST">Perder</button><button class="action" data-settle="${t.id}" data-s="VOID">Anular</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan=7>Sin tickets.</td></tr>';$$('[data-settle]').forEach(b=>b.onclick=()=>settleTicket(b.dataset.settle,b.dataset.s))}
async function settleTicket(id,status){if(!confirm('¿Liquidar ticket como '+status+'?'))return;try{await api('/api/admin/tickets/'+id+'/settle',{method:'POST',body:JSON.stringify({status})});await Promise.all([stats(),tickets()]);toast('Ticket liquidado')}catch(e){toast(e.message)}}
async function events(){const d=await api('/api/admin/events');$("#eventsBody").innerHTML=d.events.map(e=>`<tr><td><b>${esc(e.home_team)} vs ${esc(e.away_team)}</b><small>${esc(e.league)}</small></td><td>${esc(e.sport)}</td><td>${new Date(e.starts_at).toLocaleString('es-MX')}</td><td><span class=pill>${esc(e.status)}</span></td><td>${e.selections_count}</td><td><button class=action data-markets="${e.id}">Mercados</button><button class=action data-close-event="${e.id}">Cerrar</button><button class=action data-delete-event="${e.id}">Eliminar</button></td></tr>`).join('')||'<tr><td colspan=6>Sin eventos.</td></tr>';$$('[data-markets]').forEach(b=>b.onclick=()=>marketsModal(b.dataset.markets));$$('[data-close-event]').forEach(b=>b.onclick=()=>updateEvent(b.dataset.closeEvent,{status:'CLOSED'}));$$('[data-delete-event]').forEach(b=>b.onclick=()=>deleteEvent(b.dataset.deleteEvent))}
function newEvent(){openModal('Nuevo evento',`<div class=formgrid><input id=esport placeholder="Deporte"><input id=eleague placeholder="Liga"><input id=ehome placeholder="Local"><input id=eaway placeholder="Visitante"><input id=estarts type=datetime-local><select id=efeatured><option value=false>Normal</option><option value=true>Destacado</option></select><select id=evideo><option value=false>Sin video</option><option value=true>Video</option></select></div><button id=saveEvent class=primary>Crear evento</button>`);$("#saveEvent").onclick=async()=>{try{await api('/api/admin/events',{method:'POST',body:JSON.stringify({sport:$("#esport").value,league:$("#eleague").value,homeTeam:$("#ehome").value,awayTeam:$("#eaway").value,startsAt:$("#estarts").value,featured:$("#efeatured").value==='true',video:$("#evideo").value==='true'})});$("#modal").classList.add('hidden');await Promise.all([events(),stats()]);toast('Evento creado')}catch(e){toast(e.message)}}}
async function updateEvent(id,body){try{await api('/api/admin/events/'+id,{method:'PATCH',body:JSON.stringify(body)});await events();toast('Evento actualizado')}catch(e){toast(e.message)}}
async function deleteEvent(id){if(!confirm('¿Eliminar este evento y sus mercados?'))return;try{await api('/api/admin/events/'+id,{method:'DELETE'});await Promise.all([events(),stats()]);toast('Evento eliminado')}catch(e){toast(e.message)}}
async function marketsModal(eventId){try{const d=await api('/api/admin/events/'+eventId+'/markets');openModal('Mercados y cuotas',`<div class=history>${d.markets.map(m=>`<div><b>${esc(m.name)}</b>${(m.selections||[]).map(s=>`<p>${esc(s.label)} <b>${Number(s.odds).toFixed(2)}</b> <button class=action data-odd="${s.id}">Editar cuota</button></p>`).join('')}</div>`).join('')||'<p>Sin mercados.</p>'}</div><hr><h3>Agregar mercado</h3><div class=formgrid><input id=mname placeholder="Nombre, ej. Más/Menos 2.5"><input id=mtype placeholder="Tipo"></div><textarea id=msels rows=5 placeholder='Una selección por línea: Local|1|1.80'></textarea><button id=saveMarket class=primary>Agregar mercado</button>`);$$('[data-odd]').forEach(b=>b.onclick=()=>editOdd(b.dataset.odd,eventId));$("#saveMarket").onclick=async()=>{try{const selections=$("#msels").value.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const p=x.split('|');return{label:p[0],code:p[1]||'',odds:Number(p[2])}});await api('/api/admin/events/'+eventId+'/markets',{method:'POST',body:JSON.stringify({name:$("#mname").value,marketType:$("#mtype").value||'CUSTOM',selections})});await marketsModal(eventId);toast('Mercado creado')}catch(e){toast(e.message)}}}catch(e){toast(e.message)}}
async function editOdd(id,eventId){const v=prompt('Nueva cuota');if(v===null)return;try{await api('/api/admin/selections/'+id,{method:'PATCH',body:JSON.stringify({odds:Number(v)})});await marketsModal(eventId);toast('Cuota actualizada')}catch(e){toast(e.message)}}
async function quinielas(){const d=await api('/api/admin/quinielas');$("#quinielasBody").innerHTML=d.quinielas.map(q=>`<tr><td><b>${esc(q.name)}</b><small>${esc(q.description||'')}</small></td><td>${esc(q.kind)}</td><td>${money(q.price_cents)}</td><td>${q.close_at?new Date(q.close_at).toLocaleString('es-MX'):'—'}</td><td><span class=pill>${q.active?'Activa':'Inactiva'}</span></td><td><button class=action data-toggle-q="${q.id}" data-active="${q.active}">${q.active?'Desactivar':'Activar'}</button></td></tr>`).join('')||'<tr><td colspan=6>Sin quinielas.</td></tr>';$$('[data-toggle-q]').forEach(b=>b.onclick=()=>toggleQ(b.dataset.toggleQ,b.dataset.active==='true'))}
function newQuiniela(){openModal('Nueva quiniela',`<div class=formgrid><input id=qname placeholder="Nombre"><input id=qkind placeholder="Tipo: FACIL"><input id=qprice type=number placeholder="Precio en centavos"><input id=qclose type=datetime-local></div><textarea id=qdesc rows=3 placeholder="Descripción"></textarea><input id=qprize placeholder="Texto de premios"><button id=saveQ class=primary>Crear quiniela</button>`);$("#saveQ").onclick=async()=>{try{await api('/api/admin/quinielas',{method:'POST',body:JSON.stringify({name:$("#qname").value,kind:$("#qkind").value,priceCents:Number($("#qprice").value),closeAt:$("#qclose").value||null,description:$("#qdesc").value,prizeText:$("#qprize").value})});$("#modal").classList.add('hidden');await quinielas();toast('Quiniela creada')}catch(e){toast(e.message)}}}
async function toggleQ(id,active){try{await api('/api/admin/quinielas/'+id,{method:'PATCH',body:JSON.stringify({active:!active})});await quinielas();toast('Quiniela actualizada')}catch(e){toast(e.message)}}
async function wallet(){const d=await api('/api/admin/wallet-requests');$("#walletBody").innerHTML=d.requests.map(r=>`<tr><td><b>${esc(r.user_name)}</b><small>${esc(r.user_email||'')}</small></td><td>${r.type==='DEPOSIT'?'Depósito':'Retiro'}</td><td>${money(r.amount_cents)}</td><td><span class=pill>${esc(r.status)}</span></td><td>${new Date(r.created_at).toLocaleString('es-MX')}</td><td>${r.status==='PENDING'?`<button class=action data-wallet="${r.id}" data-ws="APPROVED">Aprobar</button><button class=action data-wallet="${r.id}" data-ws="REJECTED">Rechazar</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan=6>Sin solicitudes.</td></tr>';$$('[data-wallet]').forEach(b=>b.onclick=()=>resolveWallet(b.dataset.wallet,b.dataset.ws))}
async function resolveWallet(id,status){if(!confirm('¿'+status+' solicitud?'))return;try{await api('/api/admin/wallet-requests/'+id+'/resolve',{method:'POST',body:JSON.stringify({status})});await Promise.all([wallet(),stats()]);toast('Solicitud actualizada')}catch(e){toast(e.message)}}
async function audit(){const d=await api('/api/admin/audit');$("#auditBody").innerHTML=d.audit.map(a=>`<tr><td>${esc(a.admin_name)}</td><td>${esc(a.action)}</td><td>${esc(a.target_type||'')}<small>${esc(a.target_id||'')}</small></td><td><small>${esc(JSON.stringify(a.details||{}))}</small></td><td>${new Date(a.created_at).toLocaleString('es-MX')}</td></tr>`).join('')||'<tr><td colspan=5>Sin registros.</td></tr>'}
$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent='';try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({identifier:$("#email").value,password:$("#password").value})});await boot();if(!$("#app").classList.contains('hidden'))toast('Sesión iniciada')}catch(e){$("#loginError").textContent=e.message}};
$("#logout").onclick=async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()};$("#closeModal").onclick=()=>$("#modal").classList.add('hidden');$("#refreshUsers").onclick=users;$("#refreshTickets").onclick=tickets;$("#refreshEvents").onclick=events;$("#refreshQuinielas").onclick=quinielas;$("#refreshWallet").onclick=wallet;$("#refreshAudit").onclick=audit;$("#newEvent").onclick=newEvent;$("#newQuiniela").onclick=newQuiniela;$("#userSearch").oninput=()=>users();
$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));['users','tickets','events','quinielas','wallet','audit'].forEach(v=>$("#"+v+"View").classList.toggle('hidden',b.dataset.view!==v))});boot();
