const DATA=[{id:1,sport:"Fútbol",league:"Liga MX • México",home:"América",away:"Tigres",min:63,score:[2,1],odds:[1.65,3.9,4.8],video:true,featured:true},{id:2,sport:"Fútbol",league:"LaLiga • España",home:"Barcelona",away:"Real Madrid",min:72,score:[1,1],odds:[2.15,3.25,3.05],video:true,featured:true},{id:3,sport:"Fútbol",league:"Premier League • Inglaterra",home:"Manchester City",away:"Liverpool",min:81,score:[2,2],odds:[2.05,3.4,2.95],video:true,featured:false},{id:4,sport:"Básquetbol",league:"NBA • USA",home:"Lakers",away:"Celtics",min:38,score:[87,84],odds:[1.8,1.95],video:true,featured:true},{id:5,sport:"Tenis",league:"ATP • Internacional",home:"Alcaraz",away:"Sinner",min:2,score:["1","0"],odds:[1.55,2.35],video:false,featured:true},{id:6,sport:"Béisbol",league:"MLB • USA",home:"Dodgers",away:"Yankees",min:6,score:[3,2],odds:[1.72,2.1],video:true,featured:false}];
let matches=JSON.parse(JSON.stringify(DATA)),sport="Todos",filter="all",mode="single",slip=[],balance=+localStorage.getItem("bl_balance")||10000,history=JSON.parse(localStorage.getItem("bl_history")||"[]");
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),money=n=>"$"+(+n).toLocaleString("es-MX",{minimumFractionDigits:2,maximumFractionDigits:2});
function save(){localStorage.setItem("bl_balance",balance);localStorage.setItem("bl_history",JSON.stringify(history))}
function toast(s){let t=$("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function setSport(s){sport=s;$$(".sport,.side").forEach(x=>x.classList.toggle("active",x.dataset.sport===s));render()}
function list(){let q=$("#search").value.toLowerCase();return matches.filter(m=>(sport=="Todos"||m.sport==sport)&&(!q||`${m.home} ${m.away} ${m.league}`.toLowerCase().includes(q))).filter(m=>filter=="all"||filter=="featured"&&m.featured||filter=="video"&&m.video||filter=="goals"&&(m.score[0]+m.score[1]>0))}
function card(m){let labs=m.odds.length==3?["1","X","2"]:["1","2",""];return `<article class="match"><div class="matchtop"><span>${m.league}</span><span class="live">● EN VIVO ${m.min}'</span><span>${m.video?"▶ VIDEO":""}</span></div><div class="event"><button class="star">☆</button><div class="team">${m.home}<small>${m.score[0]}</small></div>${labs.map((l,i)=>l?`<button class="odd ${slip.some(x=>x.id==m.id&&x.market==l)?"selected":""}" data-id="${m.id}" data-market="${l}" data-odd="${m.odds[i]}"><small>${l}</small><b>${m.odds[i].toFixed(2)}</b></button>`:"<span></span>").join("")}<span class="more">+8</span></div><div class="event" style="padding-top:0"><span></span><div class="team">${m.away}<small>${m.score[1]}</small></div><span></span><span></span><span></span><span></span></div></article>`}
function render(){let l=list();$("#balance").textContent=money(balance);$("#allCount").textContent=matches.length;$("#eventCount").textContent=l.length+" eventos";$("#matches").innerHTML=l.map(card).join("");$$(".odd").forEach(b=>b.onclick=()=>pick(+b.dataset.id,b.dataset.market,+b.dataset.odd));renderSlip();renderHistory()}
function pick(id,market,odd){let m=matches.find(x=>x.id==id),i=slip.findIndex(x=>x.id==id);if(i>=0){if(slip[i].market==market)slip.splice(i,1);else slip[i]={id,market,odd,home:m.home,away:m.away,league:m.league}}else slip.push({id,market,odd,home:m.home,away:m.away,league:m.league});if(mode=="single"&&slip.length>1)slip=slip.slice(-1);render()}
function odds(){return slip.length?slip.reduce((a,x)=>a*x.odd,1):0}
function renderSlip(){if(!slip.length)$("#slipItems").innerHTML='<div class="empty">Selecciona un momio para agregarlo a tu boleto.</div>';else $("#slipItems").innerHTML=slip.map((x,i)=>`<div class="slip-item"><button class="remove" data-r="${i}">×</button><b>${x.home} vs ${x.away}</b><small>${x.league} · ${x.market} · ${x.odd.toFixed(2)}</small></div>`).join("");$$("[data-r]").forEach(b=>b.onclick=()=>{slip.splice(+b.dataset.r,1);render()});let o=odds(),st=+$("#stake").value||0;$("#totalOdds").textContent=o.toFixed(2);$("#potential").textContent=money(o*st);$("#mobileCount").textContent=slip.length;$("#mobilePotential").textContent=money(o*st);$("#placeBet").disabled=!slip.length||st<1||st>balance}
function renderHistory(){if(!history.length){$("#history").innerHTML='<div class="empty">No tienes apuestas virtuales todavía.</div>';return}$("#history").innerHTML=history.map(h=>`<div class="history-card"><div class="row"><b>${money(h.stake)} · Cuota ${h.odds.toFixed(2)}</b><span class="status">PENDIENTE</span></div><small>${h.date} · Potencial ${money(h.potential)}</small><p>${h.items.map(x=>x.home+" "+x.market+" "+x.odd.toFixed(2)).join(" · ")}</p></div>`).join("")}
function view(v){$("#liveView").classList.toggle("hidden",v!="live");$("#betsView").classList.toggle("hidden",v!="bets");render()}
$("#placeBet").onclick=()=>{let st=+$("#stake").value||0;if(!slip.length||st<1||st>balance)return;let o=odds();balance-=st;history.unshift({date:new Date().toLocaleString("es-MX"),stake:st,odds:o,potential:st*o,items:[...slip]});slip=[];save();render();toast("Apuesta virtual aceptada ✓")};$("#clear").onclick=()=>{slip=[];render()};$("#stake").oninput=renderSlip;$$(".quick button").forEach(b=>b.onclick=()=>{$("#stake").value=b.dataset.a;renderSlip()});$$(".sport,.side").forEach(b=>b.onclick=()=>setSport(b.dataset.sport));$$(".filters button").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$(".filters button").forEach(x=>x.classList.toggle("active",x==b));render()});$$(".slip-mode button").forEach(b=>b.onclick=()=>{mode=b.dataset.type;$$(".slip-mode button").forEach(x=>x.classList.toggle("active",x==b));if(mode=="single"&&slip.length>1)slip=slip.slice(0,1);render()});$$("[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view));$("#search").oninput=render;$("#menuBtn").onclick=()=>$("#drawer").classList.remove("hidden");$("#close").onclick=()=>$("#drawer").classList.add("hidden");$("#mobileSlip").onclick=()=>$("#betSlip").classList.toggle("mobile-open");$("#reset").onclick=()=>{balance=10000;history=[];slip=[];save();render();toast("Saldo reiniciado")};
setInterval(()=>{matches.forEach(m=>{if(Math.random()<.5)m.min=m.min>=89?1:m.min+1;m.odds=m.odds.map(o=>Math.max(1.05,Math.min(12,o*(1+(Math.random()-.5)*.035))));if(Math.random()<.02&&m.sport=="Fútbol"){let s=Math.random()<.5?0:1;m.score[s]++;toast("⚽ Gol virtual: "+(s?m.away:m.home))}});render()},3500);render();