const M=[["Fútbol","Liga MX","América","Tigres",[2,1],[1.65,3.9,4.8],1],["Fútbol","LaLiga","Barcelona","Real Madrid",[1,1],[2.15,3.25,3.05],1],["Fútbol","Premier League","Man City","Liverpool",[2,2],[2.05,3.4,2.95],0],["Básquetbol","NBA","Lakers","Celtics",[87,84],[1.8,1.95],1],["Tenis","ATP","Alcaraz","Sinner",["1","0"],[1.55,2.35],1],["Béisbol","MLB","Dodgers","Yankees",[3,2],[1.72,2.1],0]].map((x,i)=>({id:i+1,sport:x[0],league:x[1],home:x[2],away:x[3],score:x[4],odds:x[5],featured:x[6],min:20+i*9,video:i!==4}));
let sport="Todos",filter="all",slip=[],type="single",balance=+localStorage.bl_balance||10000,history=JSON.parse(localStorage.bl_history||"[]"),quick=null,quickMode=false;
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),money=n=>"$"+(+n).toLocaleString("es-MX",{minimumFractionDigits:2});
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1700)}
function save(){localStorage.bl_balance=balance;localStorage.bl_history=JSON.stringify(history)}
function render(){let q=$("#search").value.toLowerCase(),a=M.filter(m=>(sport=="Todos"||m.sport==sport)&&(!q||(`${m.home} ${m.away} ${m.league}`).toLowerCase().includes(q))).filter(m=>filter=="all"||filter=="featured"&&m.featured||filter=="video"&&m.video||filter=="goals"&&(m.score[0]+m.score[1]>0));$("#balance").textContent=money(balance);$("#count").textContent=a.length+" eventos";$("#matches").innerHTML=a.map(m=>`<article class=match><div class=matchtop><span>${m.league}</span><span class=live>● EN VIVO ${m.min}'</span><span>${m.video?"▶ VIDEO":""}</span></div><div class=event><span>☆</span><div class=team>${m.home}<small>${m.score[0]}</small></div>${m.odds.map((o,i)=>`<button class="odd ${slip.some(x=>x.id==m.id&&x.i==i)?"sel":""}" data-id=${m.id} data-i=${i}><small>${m.odds.length==3?["1","X","2"][i]:"1/2"}</small><b>${o.toFixed(2)}</b></button>`).join("")}<span class=more>+8</span></div><div class=event style="padding-top:0"><span></span><div class=team>${m.away}<small>${m.score[1]}</small></div></div></article>`).join("");$$(".odd").forEach(b=>b.onclick=()=>pick(+b.dataset.id,+b.dataset.i));renderSlip();renderHistory()}
function pick(id,i){let m=M.find(x=>x.id==id),x={id,i,odd:m.odds[i],home:m.home,away:m.away,league:m.league};if(quickMode){quick=x;$("#qselection").innerHTML=`<b>${x.home} vs ${x.away}</b><br>${x.league} · ${x.odd.toFixed(2)}`;$("#qbet").disabled=false;return}let p=slip.findIndex(y=>y.id==id);if(p>=0)slip.splice(p,1);else{if(type=="single")slip=[];slip.push(x)}render()}
function renderSlip(){let o=slip.reduce((a,x)=>a*x.odd,1),st=+$("#stake").value||0;$("#slipItems").innerHTML=slip.length?slip.map((x,i)=>`<div class=slip-item><button class=remove data-r=${i}>×</button><b>${x.home} vs ${x.away}</b><small>${x.league} · ${x.odd.toFixed(2)}</small></div>`).join(""):"<div class=empty>Selecciona un momio para agregarlo.</div>";$$(".remove").forEach(b=>b.onclick=()=>{slip.splice(+b.dataset.r,1);render()});$("#odds").textContent=slip.length?o.toFixed(2):"0.00";$("#potential").textContent=money(o*st);$("#mobileCount").textContent=slip.length;$("#mobilePot").textContent=money(o*st);$("#bet").disabled=!slip.length||st<1||st>balance}
function renderHistory(){$("#history").innerHTML=history.length?history.map(h=>`<div class=slip-item><b>${money(h.stake)} · Cuota ${h.odds.toFixed(2)}</b><small>${h.date} · Potencial ${money(h.potential)}</small></div>`).join(""):"<div class=empty>No hay apuestas.</div>"}
$$("[data-sport]").forEach(b=>b.onclick=()=>{sport=b.dataset.sport;$$("[data-sport]").forEach(x=>x.classList.toggle("active",x.dataset.sport==sport));render()});$$("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$("[data-filter]").forEach(x=>x.classList.toggle("active",x==b));render()});$("#search").oninput=render;$("#stake").oninput=renderSlip;$$(".quickmoney button").forEach(b=>b.onclick=()=>{$("#stake").value=b.dataset.a;renderSlip()});$("#clear").onclick=()=>{slip=[];render()};$$("[data-type]").forEach(b=>b.onclick=()=>{type=b.dataset.type;$$("[data-type]").forEach(x=>x.classList.toggle("active",x==b));if(type=="single"&&slip.length>1)slip=slip.slice(-1);render()});
$$("[data-tab]").forEach(b=>b.onclick=()=>{quickMode=b.dataset.tab=="quick";$("#normalPanel").classList.toggle("hidden",quickMode);$("#quickPanel").classList.toggle("hidden",!quickMode);$$("[data-tab]").forEach(x=>x.classList.toggle("active",x==b))});
$("#bet").onclick=()=>{let st=+$("#stake").value;if(st<1||st>balance)return toast("Saldo insuficiente");let o=slip.reduce((a,x)=>a*x.odd,1);balance-=st;history.unshift({stake:st,odds:o,potential:st*o,date:new Date().toLocaleString("es-MX")});slip=[];save();render();toast("Apuesta aceptada ✓")};
$$(".quickmoney button").forEach(b=>b.onclick=()=>$("#stake").value=b.dataset.a);$("#qbet").onclick=()=>{let st=+$("#qstake").value;if(!quick||st<1||st>balance)return toast("Importe inválido");balance-=st;history.unshift({stake:st,odds:quick.odd,potential:st*quick.odd,date:new Date().toLocaleString("es-MX")});quick=null;$("#qselection").textContent="Ningún momio seleccionado.";$("#qbet").disabled=true;save();render();toast("Apuesta rápida aceptada ✓")};
$("#showBets").onclick=()=>{$("#events").classList.add("hidden");$("#bets").classList.remove("hidden");renderHistory()};$("#showLive").onclick=()=>{$("#bets").classList.add("hidden");$("#events").classList.remove("hidden")};$("#mobileSlip").onclick=()=>$("#betSlip").classList.toggle("mobile-open");$("#menu").onclick=()=>toast("Usa la barra de deportes");
function openAuth(){$("#auth").classList.remove("hidden");$("#loginBox").classList.remove("hidden");$("#registerBox").classList.add("hidden")}$("#account").onclick=openAuth;$("#closeAuth").onclick=()=>$("#auth").classList.add("hidden");$("#registerLink").onclick=()=>{$("#loginBox").classList.add("hidden");$("#registerBox").classList.remove("hidden")};$("#loginLink").onclick=()=>{$("#registerBox").classList.add("hidden");$("#loginBox").classList.remove("hidden")};
async function hp(s){let b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function accs(){try{return JSON.parse(localStorage.bl_accounts||"[]")}catch{return[]}}
$("#register").onclick=async()=>{let n=$("#rn").value.trim(),c=$("#rc").value.trim().toLowerCase(),p=$("#rp").value;if(n.length<2||c.length<5||p.length<8)return toast("Completa los datos");let a=accs();if(a.some(x=>x.c==c))return toast("Cuenta ya registrada");let id=crypto.randomUUID();a.push({id,n,c,h:await hp(p)});localStorage.bl_accounts=JSON.stringify(a);localStorage.bl_session=id;$("#auth").classList.add("hidden");toast("Cuenta creada ✓")};
$("#login").onclick=async()=>{let c=$("#lc").value.trim().toLowerCase(),p=$("#lp").value,a=accs().find(x=>x.c==c);if(!a||await hp(p)!=a.h)return toast("Datos incorrectos");localStorage.bl_session=a.id;$("#auth").classList.add("hidden");toast("Sesión iniciada ✓")};
$$("[data-oauth]").forEach(b=>b.onclick=()=>toast("Google/Facebook necesita OAuth real en backend"));
setInterval(()=>{M.forEach(m=>{m.min=m.min>=89?1:m.min+1;m.odds=m.odds.map(o=>Math.max(1.05,Math.min(10,o*(1+(Math.random()-.5)*.025))))});render()},4000);render();