const M=[["Fútbol","Liga MX","América","Tigres",[2,1],[1.65,3.9,4.8],1],["Fútbol","LaLiga","Barcelona","Real Madrid",[1,1],[2.15,3.25,3.05],1],["Fútbol","Premier League","Man City","Liverpool",[2,2],[2.05,3.4,2.95],0],["Básquetbol","NBA","Lakers","Celtics",[87,84],[1.8,1.95],1],["Tenis","ATP","Alcaraz","Sinner",["1","0"],[1.55,2.35],1],["Béisbol","MLB","Dodgers","Yankees",[3,2],[1.72,2.1],0]].map((x,i)=>({id:i+1,sport:x[0],league:x[1],home:x[2],away:x[3],score:x[4],odds:x[5],featured:x[6],min:20+i*9,video:i!==4}));
let sport="Todos",filter="all",slip=[],type="single",quick=null,quickMode=false,user=null;
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),money=c=>"$"+(Number(c)/100).toLocaleString("es-MX",{minimumFractionDigits:2}),toast=t=>{let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)};
async function api(url,opt={}){let r=await fetch(url,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt});let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Error");return d}
async function loadMe(){try{let d=await api("/api/me");user=d.user;$("#balance").textContent=money(user.balance_cents);$("#account").textContent=(user.name||"U")[0].toUpperCase()}catch{user=null;$("#balance").textContent="$0.00"}}
async function loadTickets(){if(!user){$("#history").innerHTML="<div class=empty>Inicia sesión para ver tus tickets.</div>";return}try{let d=await api("/api/tickets");$("#history").innerHTML=d.tickets.length?d.tickets.map(t=>`<div class=slip-item><b>${money(t.stake_cents)} · Cuota ${Number(t.total_odds).toFixed(2)}</b><small>${new Date(t.created_at).toLocaleString("es-MX")} · Potencial ${money(t.potential_cents)}</small></div>`).join(""):"<div class=empty>No hay tickets.</div>"}catch(e){toast(e.message)}}
function render(){let q=$("#search").value.toLowerCase(),a=M.filter(m=>(sport=="Todos"||m.sport==sport)&&(!q||(`${m.home} ${m.away} ${m.league}`).toLowerCase().includes(q))).filter(m=>filter=="all"||filter=="featured"&&m.featured||filter=="video"&&m.video||filter=="goals"&&(m.score[0]+m.score[1]>0));$("#count").textContent=a.length+" eventos";$("#matches").innerHTML=a.map(m=>`<article class=match><div class=matchtop><span>${m.league}</span><span class=live>● EN VIVO ${m.min}'</span><span>${m.video?"▶ VIDEO":""}</span></div><div class=event><span>☆</span><div class=team>${m.home}<small>${m.score[0]}</small></div>${m.odds.map((o,i)=>`<button class="odd ${slip.some(x=>x.id==m.id&&x.i==i)?"sel":""}" data-id=${m.id} data-i=${i}><small>${m.odds.length==3?["1","X","2"][i]:"1/2"}</small><b>${o.toFixed(2)}</b></button>`).join("")}<span class=more>+8</span></div><div class=event style="padding-top:0"><span></span><div class=team>${m.away}<small>${m.score[1]}</small></div></div></article>`).join("");$$(".odd").forEach(b=>b.onclick=()=>pick(+b.dataset.id,+b.dataset.i));renderSlip()}
function pick(id,i){let m=M.find(x=>x.id==id),x={id,i,odd:m.odds[i],home:m.home,away:m.away,league:m.league};if(quickMode){quick=x;$("#qselection").innerHTML=`<b>${x.home} vs ${x.away}</b><br>${x.league} · ${x.odd.toFixed(2)}`;$("#qbet").disabled=false;return}let p=slip.findIndex(y=>y.id==id);if(p>=0)slip.splice(p,1);else{if(type=="single")slip=[];slip.push(x)}render()}
function renderSlip(){let o=slip.reduce((a,x)=>a*x.odd,1),st=Math.round(Number($("#stake").value)*100)||0;$("#slipItems").innerHTML=slip.length?slip.map((x,i)=>`<div class=slip-item><button class=remove data-r=${i}>×</button><b>${x.home} vs ${x.away}</b><small>${x.league} · ${x.odd.toFixed(2)}</small></div>`).join(""):"<div class=empty>Selecciona un momio para agregarlo.</div>";$$(".remove").forEach(b=>b.onclick=()=>{slip.splice(+b.dataset.r,1);render()});$("#odds").textContent=slip.length?o.toFixed(2):"0.00";$("#potential").textContent=money(st*o);$("#ticketCount").textContent=slip.length;$("#mobileCount").textContent=slip.length;$("#mobilePot").textContent=money(st*o);$("#bet").disabled=!user||!slip.length||st<100||!user.balance_cents||st>Number(user.balance_cents)}
async function submitTicket(items,stakeCents){if(!user)return openAuth();let total=items.reduce((a,x)=>a*x.odd,1);try{await api("/api/tickets",{method:"POST",body:JSON.stringify({stakeCents,totalOdds:total,selections:items})});await loadMe();await loadTickets();toast("Ticket creado ✓")}catch(e){toast(e.message)}}
$("#bet").onclick=()=>submitTicket(slip,Math.round(Number($("#stake").value)*100));$("#qbet").onclick=()=>{let s=Math.round(Number($("#qstake").value)*100);if(!quick)return;if(s<100)return toast("Importe mínimo: $1");submitTicket([quick],s);quick=null;$("#qselection").textContent="Ningún momio seleccionado.";$("#qbet").disabled=true};
$$("[data-sport]").forEach(b=>b.onclick=()=>{sport=b.dataset.sport;$("#drawer").classList.add("hidden");render()});$$("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$("[data-filter]").forEach(x=>x.classList.toggle("active",x==b));render()});$("#search").oninput=render;$("#stake").oninput=renderSlip;$$(".quickmoney button").forEach(b=>b.onclick=()=>{$("#stake").value=Number(b.dataset.a);renderSlip()});$("#clear").onclick=()=>{slip=[];render()};$$("[data-type]").forEach(b=>b.onclick=()=>{type=b.dataset.type;$$("[data-type]").forEach(x=>x.classList.toggle("active",x==b));if(type=="single"&&slip.length>1)slip=slip.slice(-1);render()});
$$("[data-tab]").forEach(b=>b.onclick=()=>{quickMode=b.dataset.tab=="quick";$("#normalPanel").classList.toggle("hidden",quickMode);$("#quickPanel").classList.toggle("hidden",!quickMode);$$("[data-tab]").forEach(x=>x.classList.toggle("active",x==b))});
$("#menu").onclick=()=>$("#drawer").classList.remove("hidden");$("#closeDrawer").onclick=()=>$("#drawer").classList.add("hidden");$("#drawerLive").onclick=()=>{$("#bets").classList.add("hidden");$("#events").classList.remove("hidden");$("#drawer").classList.add("hidden")};$("#drawerBets").onclick=()=>{$("#events").classList.add("hidden");$("#bets").classList.remove("hidden");$("#drawer").classList.add("hidden");loadTickets()};$("#mobileSlip").onclick=()=>$("#betSlip").classList.toggle("mobile-open");$("#ticketTop").onclick=()=>{if(window.innerWidth<=700)$("#mobileSlip").click();else document.querySelector(".slip").scrollIntoView({behavior:"smooth"})};
$("#showBets").onclick=()=>{$("#events").classList.add("hidden");$("#bets").classList.remove("hidden");loadTickets()};$("#showLive").onclick=()=>{$("#bets").classList.add("hidden");$("#events").classList.remove("hidden")};
function openAuth(){if(user){toast("Sesión activa");return}$("#auth").classList.remove("hidden");$("#loginBox").classList.remove("hidden");$("#registerBox").classList.add("hidden")}$("#account").onclick=openAuth;$("#closeAuth").onclick=()=>$("#auth").classList.add("hidden");$("#registerLink").onclick=()=>{$("#loginBox").classList.add("hidden");$("#registerBox").classList.remove("hidden")};$("#loginLink").onclick=()=>{$("#registerBox").classList.add("hidden");$("#loginBox").classList.remove("hidden")};
$("#register").onclick=async()=>{try{let n=$("#rn").value.trim(),c=$("#rc").value.trim(),p=$("#rp").value;if(!n||!c||p.length<8)return toast("Completa los datos");let body=c.includes("@")?{name:n,email:c,password:p}:{name:n,phone:c,password:p};let d=await api("/api/auth/register",{method:"POST",body:JSON.stringify(body)});user=d.user;$("#auth").classList.add("hidden");await loadMe();renderSlip();toast("Cuenta creada ✓")}catch(e){toast(e.message)}};
$("#login").onclick=async()=>{try{let d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({identifier:$("#lc").value.trim(),password:$("#lp").value})});user=d.user;$("#auth").classList.add("hidden");await loadMe();renderSlip();toast("Sesión iniciada ✓")}catch(e){toast(e.message)}};
$$("[data-oauth]").forEach(b=>b.onclick=()=>toast("OAuth se configura con las variables de Google/Facebook del servidor"));
setInterval(()=>{M.forEach(m=>{m.min=m.min>=89?1:m.min+1;m.odds=m.odds.map(o=>Math.max(1.05,Math.min(10,o*(1+(Math.random()-.5)*.025))))});render()},4000);
(async()=>{await loadMe();renderSlip();render()})();